name: memcache
version: 0.3.0+2
author: Dart Team <misc@dartlang.org>
description: Dart memcache APIs
homepage: https://github.com/dart-lang/memcache
environment:
  sdk: ">=2.17.0 <3.0.0"
dev_dependencies:
  test: ^1.16.0
